// 100 Love Letters - Replace these with your own personal messages!
export const generateLoveLetters = () => [
  "You make my heart skip a beat every time you smile 💕",
  "Your laugh is the most beautiful sound in the world 🎵",
  "I fall in love with you more every single day 💖",
  "You're my favorite hello and my hardest goodbye 💝",
  "Your eyes are like stars that light up my universe ✨",
  "I love how you make ordinary moments feel magical 🌟",
  "You're the reason I believe in forever 💕",
  "Your hugs are my favorite place to be 🤗",
  "I love your beautiful soul more than words can express 💖",
  "You make everything better just by being you 🌈",
  "I love how you see the good in everyone 💕",
  "Your kindness makes the world a better place 💝",
  "I love how you make me laugh even on my worst days 😄",
  "You're my sunshine on the cloudiest days ☀️",
  "I love how you remember the little things 💖",
  "Your voice is like music to my ears 🎶",
  "I love how you dance like nobody's watching 💃",
  "You're my best friend and my greatest love 💕",
  "I love how you make me feel like I'm home 🏠",
  "Your smile can brighten even the darkest room ✨",
  "I love how you believe in me when I don't 💪",
  "You're the missing piece I never knew I needed 💖",
  "I love how you make ordinary days extraordinary 🌟",
  "Your love makes me feel invincible 💕",
  "I love how you always know what to say 💝",
  "You're my favorite adventure and my safe haven 🏔️",
  "I love how you make me want to be better 💖",
  "Your touch sends butterflies through my whole body 🦋",
  "I love how you see beauty in everything 🌸",
  "You're my favorite person to do nothing with 💕",
  "I love how you make me feel understood 💖",
  "Your presence makes any place feel like home 🏡",
  "I love how you love me unconditionally 💝",
  "You're the reason I wake up with a smile 😊",
  "I love how you make me feel special every day ✨",
  "Your love is the greatest gift I've ever received 💕",
  "I love how you make ordinary moments feel like magic 🪄",
  "You're my favorite thought and my sweetest dream 💭",
  "I love how you make me feel like I belong 💖",
  "Your heart is the most beautiful thing about you 💕",
  "I love how you make me feel brave 💪",
  "You're my favorite part of every day 🌅",
  "I love how you make me feel like I'm enough 💝",
  "Your love makes me feel like I can do anything ✨",
  "I love how you make me feel like I'm floating on clouds ☁️",
  "You're my favorite person to share secrets with 🤫",
  "I love how you make me feel like I'm the only girl in the world 👑",
  "Your love is the anchor that keeps me grounded ⚓",
  "I love how you make me feel like I'm exactly where I'm meant to be 💕",
  "You're my favorite person to be quiet with 🤍",
  "I love how you make me feel like I'm the luckiest person alive 🍀",
  "Your love makes me feel like I'm walking on sunshine ☀️",
  "I love how you make me feel like I'm the most important person in the world 💖",
  "You're my favorite person to be silly with 😜",
  "I love how you make me feel like I'm exactly who I'm supposed to be 💝",
  "Your love makes me feel like I'm living in a fairy tale 🧚‍♀️",
  "I love how you make me feel like I'm the center of your universe 🌌",
  "You're my favorite person to be serious with 🤔",
  "I love how you make me feel like I'm the most beautiful girl in the world 💕",
  "Your love makes me feel like I'm exactly where I belong 🏠",
  "I love how you make me feel like I'm the most loved person on Earth 💖",
  "You're my favorite person to be adventurous with 🗺️",
  "I love how you make me feel like I'm the most special person alive ✨",
  "Your love makes me feel like I'm living my best life 🌟",
  "I love how you make me feel like I'm the most wanted person in the world 💕",
  "You're my favorite person to be cozy with 🧸",
  "I love how you make me feel like I'm the most cherished person alive 💝",
  "Your love makes me feel like I'm exactly who you've been waiting for 💖",
  "I love how you make me feel like I'm the most appreciated person in the world 🙏",
  "You're my favorite person to be spontaneous with 🎭",
  "I love how you make me feel like I'm the most valued person alive 💎",
  "Your love makes me feel like I'm exactly what you've always dreamed of 💭",
  "I love how you make me feel like I'm the most treasured person in the world 💖",
  "You're my favorite person to be lazy with 🛋️",
  "I love how you make me feel like I'm the most precious person alive 💕",
  "Your love makes me feel like I'm exactly what makes your heart complete 💖",
  "I love how you make me feel like I'm the most important person in your life 👑",
  "You're my favorite person to be productive with 📝",
  "I love how you make me feel like I'm the most loved person in your world 💝",
  "Your love makes me feel like I'm exactly what you've been searching for 🔍",
  "I love how you make me feel like I'm the most special person in your heart 💖",
  "You're my favorite person to be creative with 🎨",
  "I love how you make me feel like I'm the most cherished person in your life 💕",
  "Your love makes me feel like I'm exactly what you've always wanted 💖",
  "I love how you make me feel like I'm the most valued person in your world 💎",
  "You're my favorite person to be thoughtful with 💭",
  "I love how you make me feel like I'm the most treasured person in your heart 💝",
  "Your love makes me feel like I'm exactly what makes your soul sing 🎵",
  "I love how you make me feel like I'm the most precious person in your life 💕",
  "You're my favorite person to be romantic with 💕",
  "I love how you make me feel like I'm the most important person in your universe 🌌",
  "Your love makes me feel like I'm exactly what you've been praying for 🙏",
  "I love how you make me feel like I'm the most special person in your world ✨",
  "You're my favorite person to be yourself with 💖",
  "I love how you make me feel like I'm the most loved person in your heart 💝",
  "Your love makes me feel like I'm exactly what you've been hoping for 💕",
  "I love how you make me feel like I'm the most cherished person in your life 💖",
  "You're my favorite person to be vulnerable with 💕",
  "I love how you make me feel like I'm the most valued person in your soul 💖",
  "Your love makes me feel like I'm exactly what completes your world 💝",
  "I love how you make me feel like I'm the most treasured person in your heart 💕",
  "You're my favorite person to share my dreams with 💭",
  "I love how you make me feel like I'm the most precious person in your life 💖",
  "Your love makes me feel like I'm exactly what you've been waiting your whole life for ⏰",
  "I love how you make me feel like I'm the most special person in your universe 🌟",
  "You're my favorite person to grow old with 👴👵",
  "I love how you make me feel like I'm the most loved person in your heart forever and always 💕💕💕"
];
